name: test
on: [push]
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Run
        run: |
          bash ./scripts/ci.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: black-myth-wu-kong-subtitles
          path: |
            ./dist/*
            ./*.zip
